version: '3.8'

services:
  jupyter:
    build: .
    container_name: practice-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    command: jupyter notebook --port=8888 --no-browser --allow-root
